version: '3.8'
services:
  qa_api:
    container_name: qa_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/app/
    depends_on:
      - qa_postgres

  qa_postgres:
    image: postgres
    restart: always
    container_name: qa_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: qa
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: